### 1- Representação de Dados em Matrizes

![](../photos/2.1.1.jpg)

![](../photos/2.1.2.jpg)

In [6]:
import pandas as pd
import numpy as np

# Criando dados de exemplo para o CSV
dados = {
    'Feature1': [1.2, 2.3, 3.1, 4.8],
    'Feature2': [5.1, 6.2, 7.4, 8.3],
    'Feature3': [9.1, 10.2, 11.3, 12.4]
}

# Criando um DataFrame
df = pd.DataFrame(dados)

# Salvando o DataFrame como um CSV (simulando o arquivo CSV)
df.to_csv('../dados/dados_features.csv', index=False)

print("CSV Simulado criado:")
print(df)

CSV Simulado criado:
   Feature1  Feature2  Feature3
0       1.2       5.1       9.1
1       2.3       6.2      10.2
2       3.1       7.4      11.3
3       4.8       8.3      12.4


In [7]:
# Carregando o CSV
df_carregado = pd.read_csv('../dados/dados_features.csv')

# Convertendo o DataFrame em uma matriz (array NumPy)
matriz = df_carregado.values

# Exibindo a matriz
print("Matriz carregada do CSV:")
print(matriz)

# Verificando o tipo da variável para garantir que é um array NumPy
print("Tipo da variável 'matriz':", type(matriz))

Matriz carregada do CSV:
[[ 1.2  5.1  9.1]
 [ 2.3  6.2 10.2]
 [ 3.1  7.4 11.3]
 [ 4.8  8.3 12.4]]
Tipo da variável 'matriz': <class 'numpy.ndarray'>


In [8]:
import pandas as pd
import numpy as np

# Criando dados de exemplo para o CSV
dados = {
    'Target': [1.4, 2.5, 3.2, 2.8],
}

# Criando um DataFrame
df = pd.DataFrame(dados)

# Salvando o DataFrame como um CSV (simulando o arquivo CSV)
df.to_csv('../dados/dados_target.csv', index=False)

print("CSV Simulado criado:")
print(df)

CSV Simulado criado:
   Target
0     1.4
1     2.5
2     3.2
3     2.8


In [9]:
# Carregando o CSV
df_carregado = pd.read_csv('../dados/dados_target.csv')

# Convertendo o DataFrame em uma matriz (array NumPy)
matriz = df_carregado.values

# Exibindo a matriz
print("Matriz carregada do CSV:")
print(matriz)

# Verificando o tipo da variável para garantir que é um array NumPy
print("Tipo da variável 'matriz':", type(matriz))

Matriz carregada do CSV:
[[1.4]
 [2.5]
 [3.2]
 [2.8]]
Tipo da variável 'matriz': <class 'numpy.ndarray'>


### 2- Organização de um Problema em Operações Matriciais

Um conjunto é linearmente dependente se podemos encontrar uma combinação linear entre eles que dê um vetor nulo com pelo menos um dos valores escalares diferente de 0.

Questão:

Bananas têm 420 mg de potássio, 27 g de carboidratos e 1,3 g de proteína. Maçãs têm 200 mg de potássio, 25 g de carboidratos e 0,5 g de proteína. 

a) Podemos dizer que bananas e maçãs são equivalentes?

$Bananas =
\begin{bmatrix}
420\\
27 \\
1,3
\end{bmatrix}
$

$Maçãs =
\begin{bmatrix}
200\\
25 \\
0,5
\end{bmatrix}
$

$VetorNulo =
\begin{bmatrix}
0\\
0 \\
0
\end{bmatrix}
$

$a1 * Bananas + a2 * Maçãs = vetoNulo$

$
\begin{equation}
    \begin{cases}
    a1*400 + a2 * 200 = 0 \\
    a1*27 + a2 * 25 = 0 \\
    a1*1,3 + a2 * 0,5 = 0
    \end{cases}
\end{equation}
$

Solucionando, conlcuimos que a1 e a2 são 0 por tanto o conjunto {bananas e maçãs} são linearmente independentes

In [15]:

bananas = np.array([420, 27, 1.3])
macas = np.array([200, 25, 0.5])

p1 = bananas[0]/macas[0]
p2 = bananas[1]/macas[1]
p3 = bananas[2]/macas[2]

print(p1, p2, p3)

2.1 1.08 2.6


b) Uma baçã é uma fruta fictícia com 300 mg de potássio, 26 g de carboidratos e 0,9 g de proteína. A baçã traz mais variedade nutricional, ou seja, o conjunto {baçãs, bananas, maçãs} é linearmente independente ou linearmente dependente?

Seguindo a mesma ideia de antes para para as maças, bananas e baçãs. Encontramos que para a1 =1, a2 = 1 e a3 = -2 o resultado é o vetor nulo, assim podemos dizer que {bananas, maçãs e baçãs} são linearmente dependentes

In [23]:
#USAR COM MODERAÇÃO

bacas = np.array([300, 26, 0.9])
bananas = np.array([420, 27, 1.3])
macas = np.array([200, 25, 0.5])


import numpy as np
# Montando a matriz
matriz = np.array([bacas, bananas, macas])

# Calculando o determinante
determinante = np.linalg.det(matriz)

# Verificando a dependência linear
if determinante != 0:
    print("O conjunto é linearmente dependente.")
else:
    print("O conjunto é linearmente independente.")


O conjunto é linearmente dependente.
