## Questão 3: SVD e Distância Cosseno

Uma matriz de dados foi decomposta usando a técnica de SVD, resultando em:

- Matriz \(U\): Representa as relações entre médicos.

$U = \begin{bmatrix}
0.3745 & 0.9507 & 0.7320 & 0.5987 & 0.1560 \\
0.1560 & 0.0581 & 0.8662 & 0.6011 & 0.7081 \\
0.0206 & 0.9699 & 0.8324 & 0.2123 & 0.1818 \\
0.1834 & 0.3042 & 0.5248 & 0.4319 & 0.2912 \\
0.6119 & 0.1395 & 0.2921 & 0.3664 & 0.4561 \\
\end{bmatrix}$


- Matriz \(S\): Matriz diagonal com valores singulares.

$S = \begin{bmatrix}
20 & 0  & 0  & 0  & 0   \\
0  & 15 & 0  & 0  & 0   \\
0  & 0  & 5  & 0  & 0   \\
0  & 0  & 0  & 2  & 0   \\
0  & 0  & 0  & 0  & 0.5 \\
\end{bmatrix}$


- Matriz \(V^T\): Representa as relações entre remédios.

$V^T = \begin{bmatrix}
0.7852 & 0.1997 & 0.5142 & 0.5924 & 0.0465 \\
0.6075 & 0.1705 & 0.0651 & 0.9489 & 0.9656 \\
0.8084 & 0.3046 & 0.0977 & 0.6842 & 0.4402 \\
0.1220 & 0.4952 & 0.0344 & 0.9093 & 0.2588 \\
0.6625 & 0.3117 & 0.5201 & 0.5467 & 0.1849 \\
\end{bmatrix}$



### Perguntas Práticas:

1. Aplique a distância cosseno entre dois vetores das colunas de U e interprete a similaridade entre dois médicos.
2. Identifique possíveis outliers com base nas matrizes U e V^T.
3. Dada a matriz S, quais são as dimensões mais importantes da decomposição SVD?



In [4]:
#Pergunta 1 
import numpy as np
from scipy.spatial.distance import cosine

U = np.array([[0.3745, 0.9507, 0.7320, 0.5987, 0.1560],
                [0.1560, 0.0581, 0.8662, 0.6011, 0.7081],
                [0.0206, 0.9699, 0.8324, 0.2123, 0.1818],
                [0.1834, 0.3042, 0.5248, 0.4319, 0.2912],
                [0.6119, 0.1395, 0.2921, 0.3664, 0.4561]])

#escolha dois vetores da coluna U
v1 = U[:,0]
v2 = U[:,1]


# Calculando a distância cosseno entre os dois vetores
distancia_cosseno = cosine(v1, v2)

# Convertendo distância cosseno em similaridade (1 - distância cosseno)
similaridade_cosseno = 1 - distancia_cosseno

# Exibindo os resultados
print(f"Distância cosseno: {distancia_cosseno}")
print(f"Similaridade cosseno: {similaridade_cosseno}")

#Distancia moderada, pois a similaridade é de 0.49

Distância cosseno: 0.5034586908608397
Similaridade cosseno: 0.4965413091391603


In [7]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial.distance import pdist, squareform


U = np.array([[0.3745, 0.9507, 0.7320, 0.5987, 0.1560],
                [0.1560, 0.0581, 0.8662, 0.6011, 0.7081],
                [0.0206, 0.9699, 0.8324, 0.2123, 0.1818],
                [0.1834, 0.3042, 0.5248, 0.4319, 0.2912],
                [0.6119, 0.1395, 0.2921, 0.3664, 0.4561]])

S = np.array([[20, 0, 0, 0, 0],
                [0, 15, 0, 0, 0],
                [0, 0, 5, 0, 0],
                [0, 0, 0, 2, 0],
                [0, 0, 0, 0, 0.5]])

Vt = np.array([[0.7852, 0.1997, 0.5142, 0.5924, 0.0465],
                [0.6075, 0.1705, 0.0651, 0.9489, 0.9656],
                [0.8084, 0.3046, 0.0977, 0.6842, 0.4402],
                [0.1220, 0.4952, 0.0344, 0.9093, 0.2588],
                [0.6625, 0.3117, 0.5201, 0.5467, 0.1849]])

distancia_cosseno = pdist(U.T,'cosine')
distancia_cosseno = squareform(distancia_cosseno)

print(distancia_cosseno)

[[0.         0.50345869 0.39427802 0.20663725 0.27694219]
 [0.50345869 0.         0.18093119 0.31957581 0.59906111]
 [0.39427802 0.18093119 0.         0.07807813 0.17473886]
 [0.20663725 0.31957581 0.07807813 0.         0.11545197]
 [0.27694219 0.59906111 0.17473886 0.11545197 0.        ]]


## Questão 4: Regressão Linear

Dado o seguinte conjunto de dados sobre o preço de casas:

$$
- Área (m²): 
\begin{pmatrix}
70 \\
100 \\
120 \\
200 \\
50 \\
80 \\
90 \\
150 \\
180 \\
250 \\
300
\end{pmatrix}
$$

$$
- Preço (mil): 
\begin{pmatrix}
200 \\
300 \\
350 \\
500 \\
150 \\
220 \\
260 \\
400 \\
450 \\
600 \\
700
\end{pmatrix}
$$


### Perguntas Práticas:

1. Utilize regressão linear para encontrar os pesos que melhor ajustam o modelo para prever o preço com base na área.
2. A partir dos dados, faça um gráfico com a linha de regressão linear.
3. Sugira transformações de features que poderiam melhorar a performance do modelo.
4. Analise o coeficiente de determinação \(R^2\) para avaliar o ajuste do modelo.



### Perguntas Teóricas:

1. **O que é a Decomposição em Valores Singulares (SVD) e qual sua utilidade?**
   - Resposta: SVD é uma técnica de decomposição de matrizes que decompõe uma matriz \(A\) em três outras matrizes \(U\), \(S\), e \(V^T\), onde \(U\) e \(V\) são ortogonais e \(S\) contém os valores singulares. SVD é útil em compressão de dados, redução de dimensionalidade e detecção de padrões.

2. **Qual a diferença entre distância cosseno e distância euclidiana?**
   - Resposta: A distância cosseno mede o ângulo entre dois vetores e avalia a similaridade em termos de direção, ignorando a magnitude. Já a distância euclidiana mede a distância direta entre os pontos, considerando a magnitude dos vetores.

3. **Explique como a SVD pode ser usada para identificar outliers em um conjunto de dados.**
   - Resposta: A SVD reduz os dados a suas componentes principais, e pontos que se desviam significativamente da reconstrução dos dados com base nessas componentes podem ser considerados outliers, pois não seguem o padrão principal do conjunto de dados.